title: Elisa Perrone
url: "https://elisaperrone.info/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Teaching" 
   link: "teaching"
 - name: "Conferences"
   link: "conferences"
 - name: "Contact"
   link: "contact"
